namespace Slic3rPostProcessingUploader.Services.Parsers.AnycubicSlicerNext
{
    internal class AnycubicSlicerNextParser(string? noteTemplate) : GcodeParserBase(noteTemplate)
    {
        protected override string SlicerName => "AnycubicSlicerNext";
        protected override string SlicerVersionPattern => @"generated by AnycubicSlicerNext (.+) on";
        protected override INoteTemplate CreateDefaultTemplate() => new AnycubicSlicerNextDefaultNoteTemplate();
        protected override bool SupportsMultiFilament => true;

        public static bool IsAnycubicSlicerNext(string gcode)
        {
            return gcode.Contains("generated by AnycubicSlicerNext");
        }
    }
}
