namespace Slic3rPostProcessingUploader.Services.Parsers.PrusaSlicer
{
    internal class PrusaParser(string? noteTemplate) : GcodeParserBase(noteTemplate)
    {
        protected override string SlicerName => "PrusaSlicer";
        protected override string SlicerVersionPattern => @"generated by PrusaSlicer (.+) on";
        protected override INoteTemplate CreateDefaultTemplate() => new PrusaDefaultNoteTemplate();

        public static bool IsPrusaSlicer(string gcode)
        {
            return gcode.Contains("generated by PrusaSlicer");
        }
    }
}
