namespace Slic3rPostProcessingUploader.Services.Parsers.FLSunSlicer
{
    internal class FLSunParser(string? noteTemplate) : GcodeParserBase(noteTemplate)
    {
        protected override string SlicerName => "FLSunSlicer";
        protected override string SlicerVersionPattern => @"generated by FlsunSlicer (.+) on";
        protected override INoteTemplate CreateDefaultTemplate() => new FLSunDefaultNoteTemplate();

        public static bool IsFLSunSlicer(string gcode)
        {
            return gcode.Contains("generated by FlsunSlicer");
        }
    }
}
