namespace Slic3rPostProcessingUploader.Services.Parsers.OrcaSlicer
{
    internal class OrcaParser(string? noteTemplate) : GcodeParserBase(noteTemplate)
    {
        protected override string SlicerName => "OrcaSlicer";
        protected override string SlicerVersionPattern => @"generated by OrcaSlicer (.+) on";
        protected override INoteTemplate CreateDefaultTemplate() => new OrcaDefaultNoteTemplate();
        protected override bool SupportsMultiFilament => true;

        public static bool IsOrcaSlicer(string gcode)
        {
            return gcode.Contains("generated by OrcaSlicer");
        }
    }
}
