name: CI

on: [push, pull_request]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.dotnet.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux, os: ubuntu-latest }
          - { name: Windows VS2022, os: windows-latest }
          - { name: MacOS, os: macos-latest }
        dotnet:
          - { name: .NET 8, version: "8.0.x" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup .NET ${{ matrix.dotnet.version }} SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - name: Enforce SDK Version
        run: dotnet new globaljson --sdk-version ${{ steps.setup-dotnet.outputs.dotnet-version }} --force
      - name: Verify SDK Installation
        run: dotnet --info
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish --configuration Release
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: publish-${{ matrix.platform.name }}-${{ matrix.dotnet.name }}
      #     path: ./publish
